import kotlin.String

/**
 * Generated by [gradle-kotlin-dsl-libs](https://github.com/jmfayard/gradle-kotlin-dsl-libs)
 *
 * Run again
 *   `$ ./gradlew syncLibs`
 * to update this file */
object Libs {
    /**
     * [ktlint website](https://github.com/shyiko/ktlint) */
    const val ktlint: String = "com.github.shyiko:ktlint:" + Versions.ktlint

    const val com_jfrog_bintray_gradle_plugin: String =
            "com.jfrog.bintray:com.jfrog.bintray.gradle.plugin:" + Versions.com_jfrog_bintray_gradle_plugin

    const val detekt_cli: String =
            "io.gitlab.arturbosch.detekt:detekt-cli:" + Versions.io_gitlab_arturbosch_detekt

    const val detekt_formatting: String =
            "io.gitlab.arturbosch.detekt:detekt-formatting:" + Versions.io_gitlab_arturbosch_detekt

    const val io_gitlab_arturbosch_detekt_gradle_plugin: String =
            "io.gitlab.arturbosch.detekt:io.gitlab.arturbosch.detekt.gradle.plugin:" + Versions.io_gitlab_arturbosch_detekt

    const val jmfayard_github_io_gradle_kotlin_dsl_libs_gradle_plugin: String =
            "jmfayard.github.io.gradle-kotlin-dsl-libs:jmfayard.github.io.gradle-kotlin-dsl-libs.gradle.plugin:" + Versions.jmfayard_github_io_gradle_kotlin_dsl_libs_gradle_plugin

    const val net_ossindex_audit_gradle_plugin: String =
            "net.ossindex.audit:net.ossindex.audit.gradle.plugin:" + Versions.net_ossindex_audit_gradle_plugin

    const val org_ajoberstar_reckon_gradle_plugin: String =
            "org.ajoberstar.reckon:org.ajoberstar.reckon.gradle.plugin:" + Versions.org_ajoberstar_reckon_gradle_plugin

    const val org_jetbrains_dokka_gradle_plugin: String =
            "org.jetbrains.dokka:org.jetbrains.dokka.gradle.plugin:" + Versions.org_jetbrains_dokka_gradle_plugin

    const val org_jetbrains_kotlin_jvm_gradle_plugin: String =
            "org.jetbrains.kotlin.jvm:org.jetbrains.kotlin.jvm.gradle.plugin:" + Versions.org_jetbrains_kotlin_jvm_gradle_plugin

    /**
     * [kotlin-scripting-compiler-embeddable website](https://kotlinlang.org/) */
    const val kotlin_scripting_compiler_embeddable: String =
            "org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable:" + Versions.org_jetbrains_kotlin

    /**
     * [kotlin-stdlib-jdk8 website](https://kotlinlang.org/) */
    const val kotlin_stdlib_jdk8: String =
            "org.jetbrains.kotlin:kotlin-stdlib-jdk8:" + Versions.org_jetbrains_kotlin

    /**
     * [kotlin-test-junit website](https://kotlinlang.org/) */
    const val kotlin_test_junit: String =
            "org.jetbrains.kotlin:kotlin-test-junit:" + Versions.org_jetbrains_kotlin

    /**
     * [kotlin-test website](https://kotlinlang.org/) */
    const val kotlin_test: String =
            "org.jetbrains.kotlin:kotlin-test:" + Versions.org_jetbrains_kotlin
}
