package:
	@cd ../../ ; \
	gradle packageTemplateGradleKotlinLib

install:
	@cd ../../ ; \
	gradle installTemplateGradleKotlinLib

verify:
	@cd ../../ ; \
	gradle verifyTemplateGradleKotlinLib

publish:
	@cd ../../ ; \
	gradle verifyTemplateGradleKotlinLib && gradle publishTemplateGradleKotlinLib

.PHONY: package install verify publish
