import kotlin.String

/**
 * Generated by [gradle-kotlin-dsl-libs](https://github.com/jmfayard/gradle-kotlin-dsl-libs)
 *
 * Run again
 *   `$ ./gradlew syncLibs`
 * to update this file */
object Libs {
    const val com_github_spotbugs_gradle_plugin: String =
            "com.github.spotbugs:com.github.spotbugs.gradle.plugin:" + Versions.com_github_spotbugs_gradle_plugin

    /**
     * [guava website](https://github.com/google/guava) */
    const val guava: String = "com.google.guava:guava:" + Versions.guava

    const val com_jfrog_bintray_gradle_plugin: String =
            "com.jfrog.bintray:com.jfrog.bintray.gradle.plugin:" + Versions.com_jfrog_bintray_gradle_plugin

    const val jmfayard_github_io_gradle_kotlin_dsl_libs_gradle_plugin: String =
            "jmfayard.github.io.gradle-kotlin-dsl-libs:jmfayard.github.io.gradle-kotlin-dsl-libs.gradle.plugin:" + Versions.jmfayard_github_io_gradle_kotlin_dsl_libs_gradle_plugin

    /**
     * [junit website](http://junit.org) */
    const val junit: String = "junit:junit:" + Versions.junit

    const val net_ossindex_audit_gradle_plugin: String =
            "net.ossindex.audit:net.ossindex.audit.gradle.plugin:" + Versions.net_ossindex_audit_gradle_plugin

    const val org_ajoberstar_reckon_gradle_plugin: String =
            "org.ajoberstar.reckon:org.ajoberstar.reckon.gradle.plugin:" + Versions.org_ajoberstar_reckon_gradle_plugin
}
