package:
	@cd ../../ ; \
	gradle packageTemplateGradleJavaLib

install:
	@cd ../../ ; \
	gradle installTemplateGradleJavaLib

verify:
	@cd ../../ ; \
	gradle verifyTemplateGradleJavaLib

publish:
	@cd ../../ ; \
	gradle verifyTemplateGradleJavaLib && gradle publishTemplateGradleJavaLib

.PHONY: package install verify publish
